spring.application.name=gym

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/GymSub
spring.datasource.username=postgres
spring.datasource.password=123

# Auto-create tables from @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true